### PR TITLE
Added capability to get CIDR base as InetAddress

### PR DESCRIPTION
**Pull request by vania-pooh**
One (e.g. me) may want to get CIDR base in addition to getting mask and doing contains check. So I extended CIDR interface with getBase() method.

### CODE REVIEW

**Comment by abedra** [comment]
Hi @vania-pooh, thanks for sending this. Apologies for the long delay in response. I'm happy to add this to the project, but can you please change `base` to `address` in the request? Address is a more logical name for this. I'll get it merged and release a new version as soon as you update the PR.

**Comment by vania-pooh** [comment]
Done.

**Comment by vania-pooh** [comment]
Squashed with my previous commit.

**Comment by abedra** [comment]
Thanks @vania-pooh!

**Comment by abedra** [comment]
I'll cut a release later this afternoon and push to maven central.

**Comment by vania-pooh** [comment]
Thank you. :)

**Comment by vania-pooh** [comment]
@abedra any news about release? :)

**Pull request merged**
